version: "3"
services:
  pitch:
    image: store/gitpitch/desktop:pro
    volumes:
      - ./:/repo
    ports:
      - 9000:9000

  node:
    build:
      context: .
    environment:
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
